project: hunyen3d
entity: null
name: null
tags: []
mode: disabled   # disabled | offline | online
id: null         # for resuming, set to the old run's id to continue the same wandb curve
resume: null     # use with id: "allow" or "must"
